### ISSUE TITLE
Cannot compile on kernel > 4.3

### ISSUE THREAD

**Issue by tjpatter** [lanconnected/EnhanceIO#5]
# make

make -C /lib/modules/4.4.5-15.26.amzn1.x86_64/build M=/root/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/kernels/4.4.5-15.26.amzn1.x86_64'
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_conf.o
/root/EnhanceIO/Driver/enhanceio/eio_conf.c: In function ‘eio_init_ssddev_props’:
/root/EnhanceIO/Driver/enhanceio/eio_conf.c:1436:2: error: implicit declaration of function ‘bio_get_nr_vecs’ [-Werror=implicit-function-declaration]
  max_nr_pages = (u_int32_t)bio_get_nr_vecs(dmc->cache_dev->bdev);

It appears the bio_get_nr_vecs function no longer exists in the kernel source.

**Comment by lanconnected** [comment]
I pulled merge from tukss repositary, it seems that he already addressed this problem. Please let me know if it compiles and runs on newer kernels, we are maintaining RHEL6 and RHEL7 kernels only for now.

**Comment by tjpatter** [comment]
Your merged copy does not seem to build.  I can build it from tukss' repository (which I did not know existed).  When building from yours using kernel:  Linux ip-10-241-16-141 4.4.5-15.26.amzn1.x86_64 #1 SMP Wed Mar 16 17:15:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I get:

make -C /lib/modules/4.4.5-15.26.amzn1.x86_64/build M=/root/EnhanceIO/Driver/enhanceio modules V=0
make[1]: Entering directory `/usr/src/kernels/4.4.5-15.26.amzn1.x86_64'
  CC [M]  /root/EnhanceIO/Driver/enhanceio/eio_ttc.o
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c: In function ‘hdd_make_request’:
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c:150:3: error: too many arguments to function ‘bio_endio’
   bio_endio(bio, -EIO);
   ^
In file included from include/linux/blkdev.h:18:0,
                 from /root/EnhanceIO/Driver/enhanceio/eio_ttc.c:28:
include/linux/bio.h:470:13: note: declared here
 extern void bio_endio(struct bio *);
             ^
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c: In function ‘eio_ttc_activate’:
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c:279:23: warning: assignment from incompatible pointer type [enabled by default]
   rq->make_request_fn = eio_make_request_fn;
                       ^
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c: In function ‘eio_make_request_fn’:
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c:563:14: warning: comparison of distinct pointer types lacks a cast [enabled by default]
  if (origmfn == eio_make_request_fn)
              ^
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c: In function ‘eio_reboot_handling’:
/root/EnhanceIO/Driver/enhanceio/eio_ttc.c:1619:11: warning: passing argument 3 of ‘wait_on_bit_lock_action’ from incompatible pointer type [enabled by default]
           TASK_UNINTERRUPTIBLE);
           ^
In file included from include/linux/completion.h:11:0,
                 from include/linux/rcupdate.h:43,
                 from include/linux/rbtree.h:34,
                 from include/linux/sched.h:22,
                 from include/linux/blkdev.h:4,
                 from /root/EnhanceIO/Driver/enhanceio/eio_ttc.c:28:
include/linux/wait.h:1143:1: note: expected ‘int (*)(struct wait_bit_key *, int)’ but argument is of type ‘int (*)(struct wait_bit_key *)’
 wait_on_bit_lock_action(unsigned long *word, int bit, wait_bit_action_f *action,
 ^
make[2]: *** [/root/EnhanceIO/Driver/enhanceio/eio_ttc.o] Error 1
make[1]: *** [_module_/root/EnhanceIO/Driver/enhanceio] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.4.5-15.26.amzn1.x86_64'
make: *** [modules] Error 2

**Comment by tjpatter** [comment]
This is using Amazon Linux's latest AMI.  Based on kernel 4.4.5-15.26.  Amazon Linux is a RHEL derivative (not sure if you are familiar with it or not).  Thank you for your continued support on this project!

**Comment by lanconnected** [comment]
should be compileable now

**Comment by hguehl** [comment]
Hi,
compiles great on RH7, with kernel-ml-4.3.3-1.el7.elrepo.x86_64. However, the Makefile tries to build rpm and this doesn't work. had to use :
make -C /lib/modules/4.3.3-1.el7.elrepo.x86_64/build/  M=/usr/src/Eio/lanconnected/EnhanceIO-master/Driver/enhanceio modules_install

I'm using it in "Write Through" mode, wot (rks great but got  kernel panic when mounting the filesystem after reboot (fixed by removing udevd 94* files, and create cache after mounting filesystem)

Thanks you

**Comment by lanconnected** [comment]
Last commit (3.2.2017) adds compile compatibility to kernels up to 4.10. Closing the issue.
